# Generated by Django 3.0.6 on 2020-05-17 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaptercreate',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classroom.Subjectcreate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chaptercreate',
            name='chapter',
            field=models.CharField(max_length=100),
        ),
    ]
