# Generated by Django 3.0.6 on 2020-05-17 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20200517_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptercreate',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='classroom.Subjectcreate'),
        ),
    ]
