# Generated by Django 3.0.6 on 2020-05-17 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_assignment_studentsolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subj', to='classroom.Chaptercreate'),
            preserve_default=False,
        ),
    ]
