# Generated by Django 3.0.6 on 2020-05-18 05:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_auto_20200517_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('videofile', models.FileField(null=True, upload_to='videos/')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chap', to='classroom.Chaptercreate')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='classroom.Subjectcreate')),
            ],
        ),
    ]
