# Generated by Django 3.0.6 on 2020-05-18 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_ass_pdf_assignmentmain_chapter_ass_studentsolution_ass'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ass_pdf',
            new_name='Asspdf',
        ),
        migrations.RenameModel(
            old_name='Chapter_ass',
            new_name='Chapterass',
        ),
        migrations.AlterField(
            model_name='asspdf',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_ass', to='classroom.Assignmentmain'),
        ),
        migrations.AlterField(
            model_name='chapterass',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='su', to='classroom.Assignmentmain'),
        ),
    ]
