# Generated by Django 3.0.6 on 2020-05-18 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_auto_20200518_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asspdf',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ass', to='classroom.Chapterass'),
        ),
        migrations.AlterField(
            model_name='studentsolution_ass',
            name='ass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sol_ass', to='classroom.Asspdf'),
        ),
    ]
