# Generated by Django 3.0.6 on 2020-05-18 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_auto_20200518_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsolution_ass',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sub_a', to='classroom.Assignmentmain'),
            preserve_default=False,
        ),
    ]
