# Generated by Django 3.0.6 on 2020-05-18 15:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_studentsolution_ass_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video_ass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('videofile', models.FileField(null=True, upload_to='ass_videos/')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_completed', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapt', to='classroom.Chapterass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_vid', to='classroom.Assignmentmain')),
            ],
        ),
    ]
