# Generated by Django 3.0.6 on 2020-05-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0013_video_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentmain',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
