# Generated by Django 3.0.6 on 2020-05-20 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0019_auto_20200519_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard_ass',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sub_assign', to='classroom.Assignmentmain'),
            preserve_default=False,
        ),
    ]
